### ISSUE TITLE
Bulk send

### ISSUE THREAD

**Issue by mostafasoufi** [anlutro/php-bulk-sms#10]
Hi @anlutro,

It's possible to send bulk?

I find `sendBulkMessages` method in `BulkSmsService` class but i'm not sure about this, because this method does not $recipient param.

Regards

**Comment by anlutro** [comment]
Documentation definitely needs some improvement here. What you do is create an array of `anlutro\BulkSms\Message` objects and pass that to `sendBulkMessages`.

**Comment by mostafasoufi** [comment]
Can you please give me some examples?

**Comment by anlutro** [comment]
Something like this. Make sure you import (use) the classes from the correct namespaces.

```
$messages = [
    new Message($recipient1, $message),
    new Message($recipient2, $message),
];
SendSms::sendBulkMessages($messages);
```
