### ISSUE TITLE
respect/validation is not update in packagist!

### ISSUE THREAD

**Issue by mostafasoufi** [anlutro/php-bulk-sms#12]
Hi @anlutro,

Please update packagist. It seems the `respect/validation` does not update and I've got the old version.

https://packagist.org/packages/anlutro/bulk-sms
```
php: >=5.4.0
anlutro/curl: 0.3.*
respect/validation: 0.8.*
```

**Comment by anlutro** [comment]
Oops! Looks like we forgot to tag after merging a pull request all the way back in 2016!

I've tagged 2.1.1 now with `~1.0` as the requirement for respect/validation.
