### ISSUE TITLE
New BulkSMS API endpoint returns http/2 response

### ISSUE THREAD

**Issue by ageissel** [anlutro/php-bulk-sms#15]
Migration of BulkSMS to newer APIs return http/2 headers, which in turn do NOT respond with "200 OK".

Expect a matching pull request for cURL library.

Thank you.

**Comment by anlutro** [comment]
Thanks for the report! HTTP2 support was added in 1.4.6 of my ancient curl library: https://github.com/anlutro/php-curl/commit/da458fdd88bd132c83e7b9170c8cf1f6576fe96f#diff-e1ee2fcc629f38d16eaba23b95a87eb8e7466fae0954483c4b8ca8ad78242e0a

I'll upgrade the version constraint and release a new minor version to support this.

**Comment by ageissel** [comment]
I archived my fork to keep things organised. It was the only change I needed to make. 

The last release on Packagist held dependency to cURL 0.3.0, which may also need to be updated.

Thank you Andreas.

Adrian
