### ISSUE TITLE
Laravel5 Not Working

### ISSUE THREAD

**Issue by Mohammed2050** [anlutro/php-bulk-sms#6]
What about laravel5 When i sunmit 
sudo php artisan config:publish anlutro/bulk-sms
give me error 
[InvalidArgumentException]  
  Command "config:publish" is not defined.  
  Did you mean one of these?  
      vendor:publish  
      config:clear  
      config:cache  
it try with   vendor:publish      give me 

  [RuntimeException]  
  Too many arguments.  

Help please

**Comment by anlutro** [comment]
Yeah, I haven't updated the readme since Laravel 5. I don't work with Laravel anymore and never actually used version 5 so I couldn't tell you what the right command to run is, sorry.

If you figure it out, feel free to submit a pull request for the readme.
