### ISSUE TITLE
set message

### ISSUE THREAD

**Issue by amrfayad** [anlutro/php-bulk-sms#8]
How to set message encoding to unicode

**Comment by anlutro** [comment]
I honestly don't know :(

**Comment by amrfayad** [comment]
in function sendMessage($recipient, $message, $params)
what's the use of $params ?

**Comment by anlutro** [comment]
Those are simply passed on to the BulkSMS API as POST data.

**Comment by amrfayad** [comment]
thank you for your interest 
   I found the solution

$text = 'السلام عليكم' ; 
$encodeMessage = bin2hex(mb_convert_encoding($text, "UTF-16", "UTF-8")) ; 
$output = $b->sendMessage('+201024847900',$encodeMessage, ['dca'=>'16bit']);
